In [1]:
from housing.entity.model_factory import ModelFactory, get_sample_model_config_yaml_file
import os

In [2]:
os.getcwd()

'g:\\100-days-of-dl\\Krish Naik\\FSDS Ineuron Course\\projects\\machine-learning-project\\notebooks'

In [4]:
get_sample_model_config_yaml_file(export_dir="config")

'config\\model.yaml'

In [5]:
from sklearn.linear_model import LinearRegression

In [ ]:
LinearRegression()

In [6]:
model_config_file = r"G:\100-days-of-dl\Krish Naik\FSDS Ineuron Course\projects\machine-learning-project\notebooks\config\model.yaml"

In [7]:
model_factory = ModelFactory(model_config_path=model_config_file)

In [9]:
model_list = model_factory.get_initialized_model_list()

{'fit_intercept': True}
{'n_estimators': 40, 'min_samples_leaf': 2}


In [10]:
model_list

[InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression'),
 InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), param_grid_search={'n_estimators': [50, 100, 80], 'min_samples_leaf': [2, 4, 6]}, model_name='sklearn.ensemble.RandomForestRegressor')]

In [11]:
len(model_list)

2

In [12]:
model_list[0]

InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression')

In [13]:
model_list[1]

InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), param_grid_search={'n_estimators': [50, 100, 80], 'min_samples_leaf': [2, 4, 6]}, model_name='sklearn.ensemble.RandomForestRegressor')

In [16]:
from housing.utils.main_utils import load_numpy_array_data

In [17]:
data_file_path = r"G:\100-days-of-dl\Krish Naik\FSDS Ineuron Course\projects\machine-learning-project\housing\artifact\data_transformation\2023-02-07-23-32-09\transformed_data\train\housing.npz"

In [18]:
data = load_numpy_array_data(file_path=data_file_path)

In [19]:
data

array([[-9.41350459e-01,  1.34743822e+00,  2.75635714e-02, ...,
         0.00000000e+00,  0.00000000e+00,  7.21000000e+04],
       [ 1.17178212e+00, -1.19243966e+00, -1.72201763e+00, ...,
         0.00000000e+00,  2.98691050e+00,  2.79600000e+05],
       [ 2.67581180e-01, -1.25971599e-01,  1.22045984e+00, ...,
         0.00000000e+00,  0.00000000e+00,  8.27000000e+04],
       ...,
       [-1.57079420e+00,  1.31001828e+00,  1.53856552e+00, ...,
         0.00000000e+00,  0.00000000e+00,  1.40400000e+05],
       [-1.56080303e+00,  1.24921090e+00, -1.16533270e+00, ...,
         0.00000000e+00,  0.00000000e+00,  2.58100000e+05],
       [-1.28105026e+00,  2.02567448e+00, -1.31489265e-01, ...,
         0.00000000e+00,  0.00000000e+00,  6.27000000e+04]])

In [21]:
X, y = data[:,:-1], data[:,-1]

In [22]:
X

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [23]:
y

array([ 72100., 279600.,  82700., ..., 140400., 258100.,  62700.])

In [24]:
best_model = model_factory.get_best_model(X,y)

{'fit_intercept': True}
{'n_estimators': 40, 'min_samples_leaf': 2}
{'cv': 4, 'verbose': 2}
Fitting 4 folds for each of 2 candidates, totalling 8 fits
[CV] END .................................fit_intercept=True; total time=   0.9s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
{'cv': 4, 'verbose': 2}
Fitting 4 folds for each of 9 candidates, totalling 36 fits
[CV] END ................min_samples_leaf=2, n_estimators=50; total time=  22.0s
[CV] END ................min_samples

In [25]:
best_model

GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), best_model=RandomForestRegressor(min_samples_leaf=2), best_parameters={'min_samples_leaf': 2, 'n_estimators': 100}, best_score=0.8053536396702162)

In [27]:
best_model.model

RandomForestRegressor(min_samples_leaf=2, n_estimators=40)

In [28]:
best_model.best_model

RandomForestRegressor(min_samples_leaf=2)

In [30]:
model_factory.grid_searched_best_model_list

[GridSearchedBestModel(model_serial_number='module_0', model=LinearRegression(), best_model=LinearRegression(fit_intercept=False), best_parameters={'fit_intercept': False}, best_score=0.6393153733826),
 GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), best_model=RandomForestRegressor(min_samples_leaf=2), best_parameters={'min_samples_leaf': 2, 'n_estimators': 100}, best_score=0.8053536396702162)]

In [31]:
model_factory.grid_searched_best_model_list[0]

GridSearchedBestModel(model_serial_number='module_0', model=LinearRegression(), best_model=LinearRegression(fit_intercept=False), best_parameters={'fit_intercept': False}, best_score=0.6393153733826)

In [32]:
model_factory.grid_searched_best_model_list[1]

GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), best_model=RandomForestRegressor(min_samples_leaf=2), best_parameters={'min_samples_leaf': 2, 'n_estimators': 100}, best_score=0.8053536396702162)

In [33]:
model_factory.initialized_model_list

[InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression'),
 InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), param_grid_search={'n_estimators': [50, 100, 80], 'min_samples_leaf': [2, 4, 6]}, model_name='sklearn.ensemble.RandomForestRegressor')]